# Generated by Django 3.1.1 on 2020-09-28 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('crm', models.IntegerField(max_length=11, verbose_name='CRM')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField(max_length=7, verbose_name='Renda')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidade')),
            ],
        ),
    ]
