# Generated by Django 3.1.1 on 2020-09-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200928_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='owner',
        ),
    ]
